### ISSUE TITLE
Support for fuzzy search

### ISSUE THREAD

**Issue by thalesmello** [peco/peco#242]
Hello.

I'd like to know about the possibility of implementing a fuzzy search filter.

From what I understood about the structure of the project, it could be implemented as one of the Select Filters.

Do you think this feature would be interesting?

I'm willing to help in the implementation of this feature, but what would be some guidelines of where to start?

**Comment by lestrrat** [comment]
You mean like a word approximation type of thing? If so:

1. do I find it interesting? I'm not against the idea. I'm not ultra excited either because I don't see real case need for it (not saying there isn't one, it's just that it was not presented in your issue)
2. guidelines? er, sorry, none is available :) but you are right that Filters are where you want to look at. If you implement another filter like the RegexpFilter, then I think things would just work.

**Comment by fabriph** [comment]
+1 for the request.

I use peco as a branch switching tool, so fuzzy search would be really useful when dealing with lots of branches written in camel case. Maybe fuzzy out of the box would be expensive, but being able to activate it as a parameter would work for everyone.

**Comment by u16suzu** [comment]
+1 for the request.
