### ISSUE TITLE
Somehow join forces with fzf?

### ISSUE THREAD

**Issue by untitaker** [peco/peco#248]
[fzf](https://github.com/junegunn/fzf/) seems very similar, is written in the same language, and the two projects don't seem to know of each other.

It seems to me since there's no single definite description for what peco, fzf, selecta, fpp, etc are doing, there seems to be a lot of NIHing going on.

**Comment by lestrrat** [comment]
In spirit I agree, but I fail to see what you want us to do.

You are welcome to try and sort things out, but I bet neither team feels the need to do anything about it w/o a compelling reason to throw away the user base.

I am going to close this issue because it's vague (and, again, I fail to see what you want us to do and what you are trying to do). When you have something concrete that you like to propose, open a new issue, please.

**Comment by untitaker** [comment]
I'm not sure there's anything big to do, opening an issue was just an attempt to bring this topic up, for lack of a better way.

**Comment by lestrrat** [comment]
Yeah well... Again, I understand the general motivation, but what's the point of an issue if there's nobody who knows what to do nor wants to do anything about it.
If there's at least a proposal, we can counter it, tweak it, etc, but if it's just like "uh, there's this thing: think about it", then I don't see the point.
