### ISSUE TITLE
Remember Selected Lines when Query is Changed

### ISSUE THREAD

**Issue by aauren** [peco/peco#288]
I noticed that if I select multiple lines, that they only stay the same as long as the query stays the same. This doesn't strike me as intuitive. Why should selected lines change just because the query line was changed?

I often times find myself needing to do one query, make a couple of selections, then do another query, and make additive selections, but this doesn't seem possible in peco right now. 

Is this something that could be added?

**Comment by lestrrat** [comment]
I *think* I understand, but am not sure if my definition of "[lines] stay the same" is the same as yours. Can you be more specific?

My understanding is, given something like below (lines with '*' are meant to be the "selected" lines)

```
QUERY> foo
*fooA
 fooB
*fooC
```

And you change the query, it looks like this

```
QUERY> bar
*fooA
*fooB
  barA
  barB
```

**Comment by aauren** [comment]
@lestrrat 

Yeah, I think we're talking about the same thing. The current functionality exists as follows:
```
QUERY> foo
*foobarA
*foobarB
foobarC
```

Now type b and the following happens:
```
QUERY> foob
foobarA
foobarB
foobarC
```

Pressing enter at this point causes whatever line the selection on (likely foobarC if you were using CTRL+space) to be returned only. Instead, I feel like the following should happen after you type b:

```
QUERY> foob
* foobarA
* foobarB
foobarC
```

Pressing enter at this point would cause foobarA and foobarB to both be returned.

**Comment by aauren** [comment]
Something to consider here is whether the selection would always be visible or not. I could see both ways being both helpful and not helpful depending on how much was selected. For instance, to go back to something closer to your example what if you had:
```
QUERY> foo
* fooA
* fooB
fooC
barA
barB
```

and then removed foo as your query filter and instead typed bar you could do one of two things: 1) you could keep fooA and fooB at the top of the screen and selected so that the user is always aware of the current selection...
```
QUERY> bar
* fooA
* fooB
barA
barB
```

Or 2) you could keep them selected and just no longer display them because they don't match the filter (enter after the below would still output fooA and fooB, even though they aren't shown because the filter doesn't match them)
```
QUERY> bar
barA
barB
```

The benefits of #1 is that the user always knows what is selected at any given time. However, if the user selects a lot, it could push meaningful filter results for bar to be pushed off of the current screen. In #2 previously selected results would never interfere with the current filter (while still remaining part of the ultimate output), however, what was selected might not be quite as transparent.

**Comment by lestrrat** [comment]
[This](https://github.com/peco/peco/issues/288#issuecomment-170711134) I get and am willing to consider, but not [this](https://github.com/peco/peco/issues/288#issuecomment-170712463): main reason is that while the former suggests a very straight forward "It's the same selection, just keep it, darn it" type of action, the second requires the user to remember state -- that is, because the selection and the query may not match, you'd have to remember where some results came from either visible or not.

Having said this, I think the current implementation keeps the selection and the filtered lines as separate entities -- and this change will surely require the two to be merged. I think it's a good change, but not as trivial as the apparent result may suggest. And currently I'm low on tuits, so unless you have your life on the line unless this change be incorporated, please be patient with us :)

**Comment by aauren** [comment]
@lestrrat No worries, my life isn't on the line. = )

If I get some free time I might even play with it a little bit and if I get anything useful I'll submit a PR. Thanks for your thoughts!

**Comment by AndydeCleyre** [comment]
Can this be closed, since we have `"StickySelection": true` setting available now?

**Comment by lestrrat** [comment]
It's been left long enough, I think it's safe to close. If anything should be brought up again, we can always reopen

**Comment by aauren** [comment]
Thanks for wrapping back around to this. I didn't see that StickySelection had made it in, but that solves the problem for this issue!
