### ISSUE TITLE
v.0.3.6 please

### ISSUE THREAD

**Issue by fasterit** [peco/peco#298]
Can you please do a new release?
Readme.md describes peco.ExecuteCommand and it is a bit mean to not find that in the current v0.3.5 release.

**Comment by lestrrat** [comment]
Thanks for the poke, I guess we've been waiting for more features to accumulate to do a release, but I guess it's been long enough since the previous one that I could do one.

While I can just make a release now, 1) I haven't done a review of which features have changed since the previous release, and 2) I'm about to go give a talk in an hour or so... And I'd rather not do a release in haste. I've been burned before enough times.

So please se be patient (If you are in a hurry and in the mood, you can always compile it yourself right now)
