### ISSUE TITLE
Make --select-1 work with --query

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#396]
# What is the peco version, OS, architecture? 

- peco 0.4.9 (built from master today using commit 766fdd7)
- RHEL 6.6 64-bit

# Abstract

The `--select-1` option works, but not when `--query` is specified too.

# Discussion

This works:

```
echo "a" | \peco --select-1
```

This does not:

```
echo "a\nb" | \peco --select-1 --query=a
```

Here is one of the example use cases of the latter:

```
# tcsh alias (because bash is not an option at work)
alias pcd 'dirs | peco --select-1 --query=\!*  | awk '"'"'{print $2}'"'"' | xsel -ip; cd `xsel -op`'
cd /home/$USER/foo
cd /tmp
pcd foo
```

Above, if `peco --query=foo` filters down to only one result, doing `pcd foo` will save me one key-stroke (Enter) if `--select-1` worked with `--query`.

**Comment by lestrrat** [comment]
@kaushalmodi Your second example contains a `\nb`. Is this intentional? Because that's the problem. You have more than one input

**Comment by kaushalmodi** [comment]
> Is this intentional? 

Yes! That's what I am trying to convey.. it has 2 inputs to begin with, but after `--query=a`, the filtered list has only one element -- `a`. I would have liked `--select-1` to work if the filtered number of elements after the query application is 1 as well.

**Comment by lestrrat** [comment]
But that's not what --select-1 is. It says so:

`select first item and immediately exit if the input contains only 1 item`

emphasis: if the INPUT contains only 1 item.

**Comment by kaushalmodi** [comment]
> emphasis: if the INPUT contains only 1 item.

Hmm.. In that case, is this a reasonable feature request?

**Comment by kaushalmodi** [comment]
I tried this and that of course did not work.. `peco` crashed:

```
echo "a\nb" | peco --query=a | peco --select-1
```

**Comment by lestrrat** [comment]
Okay, so that crash is a totally different problem. Please file another issue.

Back to the original problem: when you say `percol` in your previous comments, I'm not sure if you're saying `percol` works or if it's `peco`. Please clarify?

**Comment by kaushalmodi** [comment]
> Okay, so that crash is a totally different problem. Please file another issue.

Will do.

> when you say percol in your previous comments, I'm not sure if you're saying percol works or if it's peco. Please clarify?

Sorry.. I used to use percol. But my shell config had dozens of aliases with percol, so I then did `alias percol peco` :smile: This was a copy/paste issue.. I will edit that comment to avoid confusion to others.

**Comment by kaushalmodi** [comment]
That said, I also tried

```
echo "a\nb" | \grep a | peco --query=a --select-1
```

This works..

But in cases like these:

```
echo "ab\nac\nb" | \grep a | peco --query=a --select-1
```

I have no way to undo the filtering that grep did.

Here's how I would phrase the feature request:

- If the initial query (the one passed from the command line) results in the peco filtered list to contain just one element, exit peco immediately (like in `--select-1` behavior) and result that one element.

**Comment by lestrrat** [comment]
Hmm, so I know this is not the users' problem: but here's how it works:

if `--select-1` is enabled, it is trivial to check if the number of input lines == some number, because it's static. Well, it doesn't have to be, but in 99% of the cases it is.

When `--query`is used, there's an asynchronous query being executed automatically when peco is ready. The user has the chance to *change* this query while the previous query is running.

So when does `--select-1` take effect? Should we prevent the user from changing/cancelling the first query while it's running, so that we can check if the filtered result contains exactly 1 result? Or, does using --select-1 mean that for whichever query that you interactively entered, peco would exit immediately if there's one result?

I haven't really given it much thought so it's a guess, but I don't think that's the sort of experience the user wants with peco, because peco is an **interactive** filter tool. I expect people to use interactively, and applying `--select-1` to the filtered result just sounds weird.

**Comment by kaushalmodi** [comment]
Would a new switch like `--switch-1-now` justify this? In the example of the `pcd` alias above, I know the unique query string before hand, and I just want to jump to that dir immediately. If I want to pick the dir interactively, I would choose not to provide any query or a string that doesn't result in a unique match.

**Comment by lestrrat** [comment]
> If I want to pick the dir interactively, I would choose not to provide any query or a string that doesn't result in a unique match.

I'm only guessing, but the `If I want to pick the dir interactively...` bit suggests to me that you should be using grep instead of peco?

**Comment by kaushalmodi** [comment]
> If I want to pick the dir interactively... bit suggests to me that you should be using grep instead of peco?

That message didn't go across correctly.. That *If* was specific to my use case. I might use the `pcd` alias using `peco` in 2 cases, broadly speaking. 

Let say I alias `pcd` to:

```
alias pcd 'dirs | peco --THE-NEW-SWITCH --query=\!* ......'
```

Here are the 2 cases:

1. When I know the unique string (`foo`) for one of my previously visited dirs, I would do `pcd foo`. *Using `grep` to pipe results to peco works too in this use case.*
2. If I am not sure of the name, and I was to hunt around in my `dirs` history, I would do just `pcd` or `pcd f` (assuming `f` query results in multiple list items). That should also allow me to interactively delete that initial `f` query as in the usual `peco` behavior. *If I had used `grep` in this use case, it would not have worked.*

I hope this clarifies my intent a bit.

**Comment by lestrrat** [comment]
Well, yeah, okay. But then I have to go back to the original definition of peco: it's an **interactive** filtering tool.

The definition of `--select-1` is a very very specific case where the tool can determine to exit automatically without sacrificing the interactivity, and that's the only reason exist.

Now, suppose we introduce some flag that "exits if the initial query resulted in only one line", then we would need to lock the user from changing the query until the first query is done. What if the input is a dump of 5million file names (YES, this happens)? We can only wait until those 5 million lines are done processing, and that just doesn't sound right.

Creating an option that exits when any query results in 1 result also seems wrong, because then while you free the user from possibly waiting for the initial query, you still run the risk of exiting with the wrong result, because you have no way to check if the filtered result was indeed what you wanted.

You can also argue that these problems may not occur much in the wild, but they will happen, so we need to write a bunch of caveats to warn people when they do shoot themselves in their foot. Having clauses like "you can do this when you specify `--XXXX`, but you must make sure to do YYYY" is certainly a red herring for tools like this.

**Comment by kaushalmodi** [comment]
You have a valid point .. withdrawing this feature request.. I might end up with 2 flavors of pcd.. one with grep+peco and another with just peco.

**Comment by kaushalmodi** [comment]
I now have this which probably will cover all my use cases:

```
alias pcd 'dirs | \grep -P "\!*.*" | peco --select-1 --query=\!* | \\
           awk '"'"'{print $2}'"'"' | \\
           xi; cd `xo` \\
          '
```

**Comment by friederbluemle** [comment]
Sorry for replying to the this more than 2 year old issue. I'm new to `peco` - And was looking for the same exact functionality as described by @kaushalmodi.

**Specify an initial query, and if there is only one result immediately select that line and exit?** I'm trying to avoid an unnecessary enter press when selecting a directory. On the other hand, I also want to be able to only pass a partial match, or no initial query at all, and then expect peco to show the full list (interactive).
It's totally OK to "block" until the full list is filtered (in my case it won't be more than maybe a few hundred lines).

Is there anything available in a newer version of `peco` that lets me easily do that? If not, what is the recommended workaround? Thanks!

**Comment by lestrrat** [comment]
@friederbluemle maybe this is what you want?

```bash
#/bin/bash
# Usage: [command] target_directory pattern
#
# If simple name match using find against entries in a directory  produces only one entry, print that. 
# Otherwise start start peco for an interactive session
set -e

TARGET=$1
PATTERN=$2

# Read entries from directory, and perform a match using find
ents=()
while IFS= read -r -d '' ent; do
  ents+=("$ent")
done < <(find $TARGET/* -prune -name "*$PATTERN*" -print0)

# If the number of matches is less than two, bail out or print the only match
if [[ ${#ents[@]} -eq 0 ]]; then
  exit 1
elif [[ ${#ents[@]} -eq 1 ]]; then
  echo "$ents" | tr -d $'\0'
  exit 0
fi

# Otherwise, bring up peco
exec printf "%b\n" "${ents[@]}" | peco
```
