### ISSUE TITLE
comparison with fzf

### ISSUE THREAD

**Issue by nkh** [peco/peco#422]
Could you add in the description the difference between this and fzf?

**Comment by lestrrat** [comment]
I have never used fzf, so ...
PRs welcome

**Comment by hyiltiz** [comment]
I almost exclusively used `fzf` for fuzzy-searching, and from the `peco` feature description, I think they are very similar; both implemented in `go`, both aim for fast interactive fuzzy searches, both get the job done very well.

The difference I spotted is that `peco` supports multiple selections, and is too close to `pico`, another popular text editor for beginners.

**Comment by nkh** [comment]
fzf supports multiple selection too

**Comment by hyiltiz** [comment]
Oh... I never used `fzf -m` myself before. In that case, to a regular user of `fzf` like myself, I see almost complete feature parity between the two tools.

**Comment by lestrrat** [comment]
In just glancing the README for fzf for the first time in 2 years, I'm pretty sure fzf wants to do a lot more than just filtering through data while I keep rejecting PRs and issues for things that go beyond filtering. For example, I don't think I will ever incorporate `--preview` from fzf (if I understand what it does correctly), because I just don't think a filter needs to be able to execute commands.

So there seems to be a philosophical difference, at least. YMMV, and I think we should really leave it at that. Meanwhile, I really don't feel like analyzing each of the features and list up a difference, so my initial comment of "PRs welcome" still stands :)
