### ISSUE TITLE
Future of layout "bottom-up"

### ISSUE THREAD

**Issue by hartwork** [peco/peco#429]
Hi!

Layout "bottom-up" seems to not only grow from the bottom but also have indices growing upwards with 0 at the bottom and show lines in reverse order. I would find it more intuitive personally, if 0 was still at the top and line order would be kept, so that the only two changes that "bottom-up" is doing is to grow upwards from the bottom and to have the filter bar down there. Or maybe split that into two different bottom modes. What do you think?

**Comment by lestrrat** [comment]
That layout has been made that way by consulting with other tools and users of said tools -- that is, it is that way because it was requested to be that way. so the short answer is no, it won't change. 

But if there is compelling reason to add another layout, that's a different story (and by compelling, I mean that there are enough users that wants it). Alternatively, if all I have to do is to merge a PR, we can always experiment with it.

I'm closing this issue for now because the short answer is "no".
