### ISSUE TITLE
Feature request - ability to select a line for editing

### ISSUE THREAD

**Issue by majuscule** [peco/peco#472]
#### What is the peco version, OS, architecture? 

N/A

#### Abstract

Feature request - ability to select a line for editing. This would be particularly useful for use with `--exec`, and would allow similar functionality to traditional history `reverse-i-search`.

**Comment by lestrrat** [comment]
Please elaborate?

**Comment by majuscule** [comment]
After finding the line I was searching for, I would like to be able to drop into an editable mode, so that I can modify the line before ending the peco session and sending the output on. This is important when I am immediately piping peco's output to another program.

**Comment by lestrrat** [comment]
Hmm, you want arbitrary editing? that's seems a bit out of scope for this tool, as it's really a grep-like pipe. 

when editing is required, our intentions were to do something like

```
peco | perl -pe "s/foo/bar/" | another-command
```

I am closing this for now, but if you think that I'm off on understanding what you want to do, please feel free to re-open and convince me otherwise
